CONFSRVDEV-27654: Mavenise repo + Refactor some packages + Remove or …
atlassian-forks/atlassian-axis-1.x pull request #1
Opened 2023-08-10 10:20 UTC by sujayopensource

Ignore compilation  Failing tests - mainly samples

mvn clean install -DskipTests compiles successfully

`[INFO] Building jar: /Users/schegde/IdeaProjects/Confluence/FORKS/atlassian-axis-1.x/target/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- jacoco-report-maven-plugin:0.1.1:process (default) @ atlassian-axis-1.x ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.github.veithen.rbeans.RBeanFactory (file:/Users/schegde/.m2/repository/com/github/veithen/rbeans/rbeans/0.1.1/rbeans-0.1.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.github.veithen.rbeans.RBeanFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] No coverage data collected; skipping execution.
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ atlassian-axis-1.x ---
[INFO] Installing /Users/schegde/IdeaProjects/Confluence/FORKS/atlassian-axis-1.x/target/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT.jar to /Users/schegde/.m2/repository/groupId/atlassian-axis-1.x/1.2.1-atlassian-1-SNAPSHOT/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT.jar
[INFO] Installing /Users/schegde/IdeaProjects/Confluence/FORKS/atlassian-axis-1.x/pom.xml to /Users/schegde/.m2/repository/groupId/atlassian-axis-1.x/1.2.1-atlassian-1-SNAPSHOT/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT.pom
[INFO] Installing /Users/schegde/IdeaProjects/Confluence/FORKS/atlassian-axis-1.x/target/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT-sources.jar to /Users/schegde/.m2/repository/groupId/atlassian-axis-1.x/1.2.1-atlassian-1-SNAPSHOT/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.769s
[INFO] Finished at: Thu Aug 10 15:47:18 IST 2023
[INFO] Final Memory: 32M/124M
`

2023-08-10 10:20 UTC, sujayopensource commented
Next is to :

1) Integrate Bamboo
2) Fix builds

2023-08-10 10:57 UTC, rjatkins commented on lib/javax.annotation.jar
Need to remove these jars from the repo altogether, since these are all mvn suppliable dependencies now. All you have to do is work out what versions it wants...

2023-08-10 10:59 UTC, rjatkins commented on pom.xml
> +            <url>https://mvnrepo.cantara.no/content/repositories/releases/</url>
What's this repository dependency for? Which code would we have to kill to get rid of it?

2023-08-10 11:00 UTC, rjatkins commented on pom.xml
> +            <artifactId>com.springsource.org.apache.oro</artifactId>
Just use oro:oro

2023-08-10 11:00 UTC, sujayopensource commented on pom.xml
> +            <url>https://mvnrepo.cantara.no/content/repositories/releases/</url>
Will remove it. That was for one of the dependencies which was removed - IBM JSSEProvider

2023-08-10 11:00 UTC, rjatkins commented on pom.xml
> +            <version>3.0.1</version>
Ensure this is our atlassian-2 patch release

2023-08-10 11:02 UTC, rjatkins commented on samples/perf/PerfService_ServiceTestCase.java
> +            s[i] = "qwertyuiop�asdfghjkl��zxcvbnm";
Fix corrupted source file

2023-08-10 11:05 UTC, rjatkins commented on src/main/java/javax/xml/messaging/Endpoint.java
Why does this repo have its own copy of any of the javax.xml.* sources? Shouldn't we just be building against an api jar?

2023-08-10 11:19 UTC, sujayopensource commented on src/main/java/javax/xml/messaging/Endpoint.java
Will check it out. Master also has as far as I have checked.

2023-08-10 11:19 UTC, rjatkins commented on src/test/java/test/lib/jakarta-oro-2.0.5.jar
Nuke these libs too

2023-08-10 11:23 UTC, rjatkins commented on test/wsdl/any/AnyTestCase.java
Where did the tests in this package go?

2023-08-10 11:23 UTC, rjatkins commented on test/wsdl/anytype/AnyService.java
Where did the tests in this directory go?

2023-08-10 11:27 UTC, rjatkins commented on src/test/java/test/wsdl/interop3/test.properties
> +test.Import1TestCase=http\://mssoapinterop.org/stkv3/wsdl/import1.wsdl
Why did the property key for this need to change? Surely it should still be under test.wsdl.interop3.import1?

2023-08-10 11:29 UTC, sujayopensource commented on test/wsdl/any/AnyTestCase.java
Feel have removed them manually. Will add them back. 

Besides - For now have ignored compilation of these tests as they depends on Sample classes that are not converted from .wsdl files yet and hence fail compilations. Would not be compiling samples at this point.

2023-08-10 11:30 UTC, sujayopensource commented on src/test/java/test/wsdl/interop3/test.properties
> +test.Import1TestCase=http\://mssoapinterop.org/stkv3/wsdl/import1.wsdl
Need to check how it changed. Tests were just moved to another package, nothing else..

2023-08-10 11:32 UTC, rjatkins commented on src/main/java/javax/xml/messaging/Endpoint.java
On second thoughts: attempting to remove these from the repo could be full of danger. There's just no guarantee that you can find exact matches for what it wants to be using in mvn, because they're so old

2023-08-10 11:33 UTC, rjatkins commented on src/test/java/test/wsdl/interop3/test.properties
> +test.Import1TestCase=http\://mssoapinterop.org/stkv3/wsdl/import1.wsdl
Something might have tried to be helpful and refactored strings as you moved things around. It's amazing that so little else changed in the whole repo

2023-08-10 11:34 UTC, rjatkins requested changes
Just need to fix up some of the libs in the repo to be maven dependencies, and I think we're good to merge this

2023-08-10 11:35 UTC, sujayopensource commented on test/wsdl/anytype/AnyService.java
Same as https://github.com/atlassian-forks/atlassian-axis-1.x/pull/1#discussion_r1289983086.

Will add the tests back , but wsdl tests would be ignored fro compilation for now as they heavily use sample classes and they dont exist for some reason in the repo.

2023-08-10 11:39 UTC, sujayopensource commented on lib/javax.annotation.jar
I missed removal of these.
Initially made it compile with ant by adding jars here and fixing compilation issues.
Will nuke the folder

2023-08-10 13:26 UTC, sujayopensource commented on src/main/java/javax/xml/messaging/Endpoint.java
Yes. Thats the reason it was retained in master too

2023-08-10 14:23 UTC, sujayopensource commented
> Just need to fix up some of the libs in the repo to be maven dependencies, and I think we're good to merge this

Ok.

The fact that the repo compiles with:
`mvn clean install -DskipTests` 
means that the libs folder is quite useless.
Confirmed by removing the lib folder locally.
But will remove it to keep repo clean and lean

2023-08-11 08:27 UTC, sujayopensource commented on pom.xml
> +            <version>3.0.1</version>
Cannot quite find this being used in confluence core
Its using:
```
<commons.httpclient.version>3.1-jenkins-3</commons.httpclient.version>

<dependency>
                <groupId>commons-httpclient</groupId>
                <artifactId>commons-httpclient</artifactId>
                <version>${commons.httpclient.version}</version>
                <exclusions>
                    <exclusion>
                        <!-- jcl-over-slf4j instead -->
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

2023-08-11 08:59 UTC, sujayopensource commented on samples/perf/PerfService_ServiceTestCase.java
> +            s[i] = "qwertyuiop�asdfghjkl��zxcvbnm";
Will fix it. 
But its a test inside samples that too. Would not be building samples at the moment.

2023-08-16 07:50 UTC, sujayopensource commented
> Just need to fix up some of the libs in the repo to be maven dependencies, and I think we're good to merge this

Fixed all the comments and it builds locally fine:

`[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ atlassian-axis-1.x ---
[INFO] Installing /Users/schegde/IdeaProjects/Confluence/FORKS/atlassian-axis-1.x/target/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT.jar to /Users/schegde/.m2/repository/groupId/atlassian-axis-1.x/1.2.1-atlassian-1-SNAPSHOT/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT.jar
[INFO] Installing /Users/schegde/IdeaProjects/Confluence/FORKS/atlassian-axis-1.x/pom.xml to /Users/schegde/.m2/repository/groupId/atlassian-axis-1.x/1.2.1-atlassian-1-SNAPSHOT/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT.pom
[INFO] Installing /Users/schegde/IdeaProjects/Confluence/FORKS/atlassian-axis-1.x/target/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT-sources.jar to /Users/schegde/.m2/repository/groupId/atlassian-axis-1.x/1.2.1-atlassian-1-SNAPSHOT/atlassian-axis-1.x-1.2.1-atlassian-1-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.793s
[INFO] Finished at: Wed Aug 16 13:06:21 IST 2023
[INFO] Final Memory: 32M/120M
[INFO] ------------------------------------------------------------------------`

2023-08-16 11:06 UTC, sujayopensource commented
> Just need to fix up some of the libs in the repo to be maven dependencies, and I think we're good to merge this

Done....

2023-08-16 11:07 UTC, sujayopensource commented
Closed by mistake!! Reopening

2023-08-16 23:25 UTC, rjatkins approved these changes
Looks good for the first pass

Next step: working tests!

2023-08-17 03:39 UTC, sujayopensource commented
> Looks good for the first pass
> 
> Next step: working tests!

Yes. Prior to that need to get Bamboo working for the repo :) ....

2023-08-17 03:39 UTC, merged